{
"prevbutton":"Prev",
"nextbutton":"Next",
"headertitle":"CIPMS-Receive",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"barcodelabel":"Barcode",
"partlabel":"Part",
"totalbundlelabel":"Total Bundles:",
"totalgarmentpcslabel":"Total Garment Pcs:",
"totalpcslabel":"Total Part Pcs:",
"confirmbutton":"Confirm",
"rejectbutton":"Reject",
"savebutton":"Save",
"querybutton":"Query",
"emptybutton":"Clear",
"fromfactoryselectlabel":"From:",
"nextfactorylabel":"To:",
"messageth":"Message",
"barcodelistlabel":"Bundle List",
"docnolabel":"Check DOC_NO",
"select":"--Select--",
"factoryselect":"--Factory--",
"processselect":"--Process--",
"productionlineselect":"--Production Line--",
"partselectmessage":"Have selected parts:",
"errormessage":"Sorry, something wrong! Pls try again! Wrong Code:",
"errormessage2":"Sorry! Something wrong with the application! Wrong Code:",
"errormessage3":"Sorry！Exists more than one line in these barcodes!",
"loadingmessage":"System is running! Please wait a minute!",
"statusmessage1":"Sorry! The barcode scanned is in submit!",
"statusmessage2":"Sorry! The barcode scanned is in different process!",
"statusmessage3":"Sorry! The barcode scanned is not have full parts!",
"statusmessage4":"Sorry! The barcode scanned is in different receive process/production!",
"statusmessage5":"Sorry! The barcode scanned is in different send process/production!",
"statusmessage6":"Sorry! Something wrong with bundle check! Pls. try again!",
"statusmessage7":"Sorry! The bundle you scanned exists multiple garment_type in CUT!",
"statusmessage8":"Sorry! The bundle you scanned exists multiple garment_type in SEW!",
"statusmessage9":"Sorry! WIP over! Wrong code:",
"statusmessage10":"Sorry! Exists double WIP!",
"statusmessage11":"Sorry! Last process' output is less than the adjustment WIP!",
"statusmessage12":"Sorry! The bundle scanned are not in matching!",
"statusmessage13":"Sorry! The carton of the bundles you scanned is not in your process!",
"statusmessage14":"Sorry! The carton of the bundles you scanned is not full!",
"statusmessage15":"Sorry! The bundle you scanned are not in matching!",
"statusmessage16":"Sorry! The bundle you scanned is in carton! Pls. scan carton barcode!",
"barcodescanmessage1":"Pls scan the barcode!",
"barcodescanmessage2":"Succeed in scanning and querying the DOC_NO:",
"barcodescanmessage3":"Pls scan DOC_NO or Bundle Barcode or Carton Barcode!",
"barcodescanmessage4":"You have scanned ",
"barcodescanmessage5":"You just can scan the bundle barcode pls!",
"barcodescanmessage6":"Sorry! Pls scan the DOC_NO into check DOC_NO first!",
"barcodescanmessage7":"Sorry! The bundle barcode you scanned is not exsit DOC_NO!",
"barcodescanmessage8":"Succeed in scanning and querying the bundle barcode:",
"barcodescanmessage9":"Sorry! The carton you scanned is not exist!",
"barcodescanmessage10":"Sorry! There is no DOC_NO with the cartorn!",
"barcodescanmessage11":"Sorry! The DOC_NO is not in submitting!",
"barcodescanmessage12":"Sorry! The DOC_NO should be received by submit user!",
"barcodescanmessage13":"Sorry! The DOC_NO should be received by next process!",
"barcodescanmessage14":"Succeed in scanning the DOC_NO of the bundle:",
"barcodescanmessage15":"Succeed in scanning the DOC_NO of the carton:",
"barcodescanmessage16":"Succeed in scanning the DOC_NO:",
"barcodescanmessage17":"Sorry! The sender and receiver of the DOC_NO should be the same!",
"barcodescanmessage18":"Sorry! The DOC_NO should be recevied by next process!",
"barcodescanmessage19":"Sorry! The barcode you scanned exists multiple DOC_NO! They should be scanned one by one!",
"barcodescanmessage20":"Sorry! Something wrong with the application of bundle status check! Pls. try again! Wrong Code:",
"partselectmessage1":"Pls select part!",
"clearmessage1":"Clear successfully!",
"savemessage1":"Succeed in saving DOC_NO:",
"querychangemessage":"Succeed in querying the DOC_NO:",
"confirmmessage1":"Succeed in receiving the DOC_NO!",
"confirmmessage2":"Successfully!",
"confirmmessage3":"Sorry! Pls select the receive production line first!",
"confirmmessage4":"Succeed in receiving the scanned bundle!",
"confirmmessage5":"Sorry! Pls. scan all the bundles in the DOCNO! Wrong Code:",
"confirmmessage6":"Sorry! Pls. scan all the bundles in the carton! Wrong Code:",
"confirmmessage7":"Sorry! There are different status of the DOCNO! Wrong Code:",
"confirmmessage8":"Sorry! The DOCNO have different receive process/production and send process/production! Wrong Code:",
"confirmmessage9":"Sorry! Receive failure! Wrong Code:831! Reason:",
"confirmmessage10":"Sorry! Receive failure! Wrong Code:",
"rejectmessage1":"Succeed in rejecting the DOC_NO:",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"outputreporta":"Output Report",
"dctreporta":"dCT Report",
"dialogmessage1":"Check",
"dialogmessage2":"No check",
"dialogmessage3":"Attention：",
"dialogmessage4":"Check the received bundles?",
"dialogmessage5":"Receive scanned bundles, reject unscanned bundles",
"dialogmessage6":"Receive",
"dialogmessage7":"Cancel",
"dialogmessage8":"您接收的裁片并不完整，所以系统将会自动打开箱子，把未扫描的裁片关成新的箱子并自动返回上道部门！    另外请问您需要把接收的裁片关箱吗？",
"dialogmessage9":"接收和关箱",
"dialogmessage10":"接收，不关箱",
"dialogmessage13":"箱内裁片完整，请问接收的箱子需要打开吗？",
"dialogmessage11":"Receive Carton",
"dialogmessage12":"Receive bundle and open Carton",
"s":"'s ",
"tabletranslation0":"DOC_NO.",
"tabletranslation1":"Carton",
"tabletranslation2":"Process",
"tabletranslation3":"Bundle_Barcode",
"tabletranslation4":"Part",
"tabletranslation5":"JO",
"tabletranslation6":"Bundle_no",
"tabletranslation7":"Lay_no",
"tabletranslation8":"Color",
"tabletranslation9":"Size",
"tabletranslation10":"Cut_Qty",
"tabletranslation11":"Output",
"tabletranslation12":"Reduce",
"tabletranslation13":"Defect",
"tabletranslation14":"Delete",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
 "printsparebarcodea":"Print Spare Code",
"wipandoutputlia":"Real-time Production Information Report "
}