{
"prevbutton":"Prev",
"nextbutton":"Next",
"pdtitle":"Print",
"pdbutton":"Print",
"headertitle":"CIPMS-Matching",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"messageth":"Message",
"matchingbutton":"Matching Carton",
"emptylistbutton":"Clear",
"savebutton":"Save",
"querybutton":"--Query--",
"select":"--Select--",
"deletebutton":"Delete",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"outputreporta":"Output Report",
"dctreporta":"dCT Report",
"bundlebarcodelabel":"Barcode",

"totalbundlelabel":"Total Bundles:",
"totalgarmentpcslabel":"Total Garment Pcs:",
"totalpartlabel":"Total Part:",
"totalpcslabel":"Total Part Pcs:",

"barcodelistlabel":"Bundle List",
"errormessage":"Sorry! Something wrong! Pls check your network! Wrong Code:",
"loadingmessage":"System is running! Please wait a minute!",
"matchingmessage3":"Matching successfully!",
"matchingmessage4":"The bundle is not in DC or You have scanned these bundles before!",
"matchingmessage1":"Succeed in scanning the Bundle Barcode: ",
"matchingmessage5":"The bundle you scan is not full so that it can not be matched!",
"matchingmessage6":"The bundle you scan is full so that it can be matched!",
"matchingmessage7":"Sorry! The bundles you scanned have been matched!",
"matchingmessage8":"Sorry! The bundles are not full! Wrong Code:",
"matchingmessage9":"Sorry! Matching failure! Wrong Code:",
"savemessage1":"Save successfully! Save time is ",
"deletemessage1":"Succeed in deleting the bundle: ",
"deletemessage2":"Succeed in deleting the carton: ",
"title1":"Carton",
"title2":"Process",
"title3":"Bundle_Barcode",
"title4":"Part",
"title5":"JO",
"title6":"Bundle_no",
"title7":"Lay_no",
"title8":"Color",
"title9":"Size",
"title10":"Cut_Qty",
"title11":"Output",
"title13":"Defect",
"title12":"Reduce",
"customer":"Customer",
"date":"Date Time",
"process":"From Dept",
"production":"Cut Line",
"sewline":"Sew Line",
"ttlbundle":"TTL Bundle",
"shortpart":"Remain Parts",
"part":"Part",
"summary":"Summary",
"jo":"JO NO.",
"color":"Color",
"cutqty":"CUT QTY",
"layno":"LAY NO",
"bundle":"TOTAL BUNDLE",
"totalqty":"TOTAL QTY",
"cartonbarcode":"Carton Barcode",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
 "printsparebarcodea":"Print Spare Code",
    "emb":"EMB",
    "prt":"PRINT",
    "embafterprt":"EMB AFTER PRINT",
    "prtsp":"PRINT/SPARE"
}