{
"functionmenubutton":"功能选择",
"headertitle":"CIPMS-员工产量",
"footertitle":"CIPMS",
"cancelbutton":"注销",
"barcodelabel":"条码",
"partlabel":"部件",
"userbarcodelabel":"用户条码",
"usernamelabel":"姓名",
"processlabel":"部门",
"productionlinelabel":"组别",
"messageth":"操作历史",
"barcodelistlabel":"已扫描裁片列表",
"totalbundlelabel":"扎数：",
"totalpcslabel":"件数：",
"select":"--选择--",
"barcodescanmessage1":"对不起！您扫描的用户条码不存在！",
"barcodescanmessage2":"对不起！您扫描的用户不属于本部门",
"barcodescanmessage3":"对不起！您扫描的裁片在 ",
"barcodescanmessage4":"对不起！您扫描的条码不存在！",
"barcodescanmessage5":"对不起！该条码已经被其他人扫描过了！扫描者为 ",
"barcodescanmessage6":"对不起！该箱码为开箱状态！",
"barcodescanmessage7":" 登录成功！",
"barcodescanmessage8":"成功! ",
"barcodescanmessage9":" 属于 ",
"errormessage":"对不起！请检查网络并重试！错误代码：",
"partselectmessage":"对不起！请先选择部件！",
"emptymessage":"成功清空界面！",
"packagea":"装箱",
"matchinga":"DC配套",
"transactiona":"流转",
"receivea":"接收",
"bundlereducea":"下数",
"printbarcodea":"打印菲纸",
"employeeoutputa":"员工产量",
"externalreceivea":"外部入数",
"bundleinputa":"按扎入数",
"reporta":"报表",
"wipreporta":"WIP报表",
"dctreporta":"dCT报表",
"outputreporta":"产量报表",
"barcodeinquirya":"扎/箱信息查询",
"docnoinquirya":"流水单信息查询",
"wipandoutputlia":"实时生产信息报表"
}