{
"functionmenubutton":"Functions",
"headertitle":"CIPMS-Employee Output",
"footertitle":"CIPMS",
"cancelbutton":"Logout",
"barcodelabel":"Barcode",
"partlabel":"Part",
"userbarcodelabel":"User Barcode",
"usernamelabel":"Name",
"processlabel":"Process",
"productionlinelabel":"Production Line",
"messageth":"Message",
"barcodelistlabel":"Bundle List",
"totalbundlelabel":"Total bundles:",
"totalpcslabel":"Total pcs:",
"select":"--Select--",
"barcodescanmessage1":"Failure! Pls scan the correct user barcode!",
"barcodescanmessage2":"Sorry! The user you scan does not belong to ",
"barcodescanmessage3":"Sorry! The barcode you scan is in ",
"barcodescanmessage4":"Failure! The barcode you scan is not exsitent!",
"barcodescanmessage5":"Failure! The barcode you scan has been scanned before by ",
"barcodescanmessage6":"Failure! The carton is not in closed!",
"barcodescanmessage7":" logins successfully!",
"barcodescanmessage8":"Successfully! ",
"barcodescanmessage9":" belongs to ",
"errormessage":"Sorry, something wrong! Pls try again! Wrong Code:",
"partselectmessage":"Pls select part first!",
"emptymessage":"Have cleared the UI!",
"packagea":"Package",
"matchinga":",Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"dctreporta":"dCT Report",
"outputreporta":"Output Report",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report "
}