{
"pdtitle":"Print",
"pdbutton":"Print",
"headertitle":"CIPMS-Register",
"footertitle":"CIPMS",
"footertitle":"Cutting Internal Panel Management System",
"backbutton":"Back",
"printbutton":"Register&Print",
"modifybutton":"Modify",
"reprintbutton":"Reprint",
"clearbutton":"Clear",
"contenttitle":"Register",
"promisebarcodelabel":"Admin Barcode",
"userbarcodelabel":"User Barcode",
"usernamelabel":"Name",
"employeenolabel":"Employee No",
"factorylabel":"Factory",
"grouplabel":"Production Line",
"shiftlabel":"Shift",
"processlabel":"Process",
"functionlabel":"Access Function",
"defaultfunctionlabel":"Default Function",
"select":"--Select--",
"errormessage":"Failure! Pls check your network and try again! Wrong Code:",
"message1":"Sorry! Please input the whole information!",
"message2":"Sorry! Your are not administrator!",
"message3":"Sorry! The Employee no is existent!",
"message4":"Succeed in modifying user information!",
"message6":"Sorry! The employee no is not existent!",
"message7":"Sorry! Pls input the employee no who need to reprint!",
"message8":"Sorry! Your user barcode is not right!",
"registernewbarcode":"Register successfully! The new user barcode can be printed!",
"reprintmessage":"Successfully! The old user barcode can be reprinted!",
"a1":"2. Package Module",
"a2":"3. Matching Module",
"a3":"5. Receive Module",
"a4":"4. Transaction Module",
"a5":"6. Reduce Module",
"a6":"1. Print Module",
"a7":"8. WIP report Module",
"a28":"9. Outout report Module",
"a29":"10. dCT report Module",
"a30":"12. Doc No. Inquiry Module",
"a31":"13. Barcode Inquiry Module",
"a27":"7. Bundle Input Module",
"a8":"11. Employee Output Module",
"a9":"a)  Close Carton",
"a10":"b)  Open Carton",
"a11":"a)  Matching",
"a12":"c)  Check Carton",
"a13":"d)  Print Carton",
"a14":"a)  Receive",
"a15":"b)  Reject",
"a16":"a)  Transaction",
"a17":"b)  Rework",
"a18":"c)  Adjustment",
"a19":"a)  Reduce",
"a20":"a)  Employee Output",
"a21":"a)  Bundle Input",
"a22":"a)  WIP Report",
"a23":"a)  Output Report",
"a24":"a)  dCT Report",
"a25":"e)  Lay_no Select",
"a26":"a)  Print",
"a33":"a)  Barcode Information Inquiry",
"a32":"a)  Doc No. Inquiry",
"a34":"13. Print Spare Code Interface",
"a35":"a)  Print Spare Code"
}