{
"pdtitle":"打印页面",
"pdbutton":"打印",
"headertitle":"CIPMS-用户注册",
"footertitle":"CIPMS",
"footertitle":"裁床内部裁片管理系统",
"backbutton":"返回",
"printbutton":"注册&打印",
"modifybutton":"修改",
"reprintbutton":"重新打印",
"clearbutton":"清空",
"contenttitle":"注册",
"promisebarcodelabel":"管理员条码",
"userbarcodelabel":"用户条码",
"usernamelabel":"姓名",
"employeenolabel":"工号",
"factorylabel":"工厂",
"grouplabel":"组别",
"shiftlabel":"班次",
"processlabel":"部门",
"functionlabel":"功能权限选择",
"defaultfunctionlabel":"默认模块界面",
"select":"--选择--",
"errormessage":"对不起！请检查您的网络并且重新尝试操作！错误代码：",
"message1":"对不起！请输入完整信息！",
"message2":"对不起！您扫描的条码不是管理员条码！",
"message3":"对不起！该用户已存在！",
"message4":"成功修改用户信息！",
"message6":"对不起！该员工号不存在！",
"message7":"对不起！请输入要重新打印条码的用户工号！",
"message8":"对不起！输入的用户条码不正确！",
"registernewbarcode":"注册成功！新用户条码已生成，可进行打印！",
"reprintmessage":"查询成功！可重新打印该用户条码！",
"a1":"2. 装箱界面",
"a2":"3. 配套界面",
"a3":"5. 接收界面",
"a4":"4. 流转界面",
"a5":"6. 下数界面",
"a6":"1. 菲纸打印界面",
"a7":"8. WIP报表界面",
"a28":"9. Output报表界面",
"a29":"10. dCT报表界面",
"a30":"12. 流水单信息查询界面",
"a31":"13. 扎/箱信息查询界面",
"a27":"7. 入数界面",
"a8":"11. 员工产量界面",
"a9":"a)  关箱",
"a10":"b)  开箱",
"a11":"a)  配套",
"a12":"c)  复核箱",
"a13":"d)  打印箱码",
"a14":"a)  接收",
"a15":"b)  拒绝接收",
"a16":"a)  流转",
"a17":"b)  返工",
"a18":"c)  调整",
"a19":"a)  下数",
"a20":"a)  员工产量",
"a21":"a)  入数",
"a22":"a)  WIP报表",
"a23":"a)  产量报表",
"a24":"a)  dCT报表",
"a25":"e)  床次选择",
"a26":"a)  打印菲纸",
"a33":"a)  扎/箱信息查询",
"a32":"a)  流水单信息查询",
"a34":"13. 打印印花士啤菲纸界面",
"a35":"a)  打印印花士啤菲纸"
}