{
    "headertitle":"CIPMS-产量WIP报表",
    "footertitle":"CIPMS",
    "functionmenubutton":"功能选择",
    "cancelbutton":"注销",
    "jotext":"制单号",
    "gotext":"GO NO.",
    "fromdatelabel":"From Date",
    "todatelabel":"To Date",
    "querybutton":"查询",
    "select":"--选择--",

    "errormessage":"对不起！请检查网络并且重新操作！错误代码:",
    "loadingmessage":"系统正在运作，请耐心等待！",
    "querymessage1":"对不起！起始日期不能大于结束日期！",
    "querymessage2":"没有数据结果！",
    "querymessage3":"请填写完整日期！",
    "querymessage4":"对不起！您输入的JO不属于输入的GO！",
    "querymessage5":"对不起！请输入查询信息！",
    "querymessage6":"对不起！用户输入的JO和GO不匹配！",
    "packagea":"装箱",
    "matchinga":"DC配套",
    "transactiona":"流转",
    "receivea":"接收",
    "bundlereducea":"下数",
    "printbarcodea":"打印菲纸",
    "employeeoutputa":"员工产量",
    "externalreceivea":"外部入数",
    "bundleinputa":"按扎入数",
    "reporta":"报表",
    "wipreporta":"WIP报表",
    "outputreporta":"流转产量报表",
    "dctreporta":"dCT报表",
    "barcodeinquirya":"扎/箱信息查询",
    "docnoinquirya":"流水单信息查询",
    "wipandoutputlia":"实时生产信息报表",

    "CUT_LINE":"裁床组别",
    "PRODUCTION_LINE_CD":"车缝组别",
    "JOB_ORDER_NO":"制单号",
    "COLOR_CD":"颜色",
    "ORDER_QTY":"订单数",
    "CUT_QTY_TODAY":"拉布产量",
    "CUT_QTY_TOTAL":"拉布总产量",
    "REDUCE_QTY_TODAY":"裁床减数",
    "REDUCE_QTY_TOTAL":"裁床总减数",
    "CUT_OUT_TODAY":"执色数",
    "CUT_OUT_TOTAL":"执色总数",
    "CUT_OUT_WIP":"待执色WIP",
    "PRT_IN_TODAY":"印花送货",
    "PRT_IN_TOTAL":"印花总送货",
    "PRT_OUT_TODAY":"印花回货",
    "PRT_OUT_TOTAL":"印花总回货",
    "PRT_IN_OUT_WIP":"待印花WIP",
    "EMB_OUT_TODAY":"绣花产量",
    "EMB_OUT_TOTAL":"绣花总产量",
    "EMB_OUT_WIP":"待绣花WIP",
    "FUSING_OUT_TODAY":"烫唛产量",
    "FUSING_OUT_TOTAL":"烫唛总产量",
    "FUSING_OUT_WIP":"待烫唛WIP",
    "MATCHING_OUT_TODAY":"待配套产量",
    "MATCHING_OUT_TOTAL":"待配套总产量",
    "MATCHING_OUT_WIP":"待配套WIP",
    "DC_BEFORE_WIP":"DC前WIP",
    "DC_SEW_S_TOTAL":"总DC WIP",
    "DC_SEW_C":"当天Output",
    "DC_SEW_C_TOTAL":"累计output",
    "TWIP":"总WIP",
    "DCT":"DCT",
    "CUT_QTY":"裁数",
    "SEQ":"顺序号",

    "GRID_FIRST":"第一页",
    "GRID_LAST":"最后页",
    "GRID_NEXT":"后一页",
    "GRID_PREVIOUS":"前一页",
    "GRID_ITEMSPERPAGE":"行/页",
    "GRID.EMPTY":"空的",
    "printsparebarcodea":"打印印花士啤菲纸",
    "GRID.SPAN1":"数据清单:"


}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          