{
    "headertitle":"CIPMS-Real-time Production Information Report",
    "footertitle":"CIPMS",
    "functionmenubutton":"Functions",
    "cancelbutton":"Logout",
    "jotext":"JO NO.",
    "gotext":"GO NO.",
    "outputlabel":"Output report:",
    "fromdatelabel":"From Date",
    "todatelabel":"To Date",
    "querybutton":"Query",
    "select":"--Select--",

    "errormessage":"Sorry! Something wrong! Pls check your network! Wrong Code:",
    "loadingmessage":"System is running! Please wait a minute!",
    "querymessage1":"Sorry! From date can not bigger than To date!",
    "querymessage2":"No data!",
    "querymessage3":"Pls input the whole date!",
    "querymessage4":"Sorry! The JO you input does not belong to the GO you input!",
    "querymessage5":"Sorry! Pls input the query condition!",
    "querymessage6":"Sorry! JO and GO are not matching!",
    "packagea":"Package",
    "matchinga":"Matching",
    "transactiona":"Transaction",
    "receivea":"Receive",
    "bundlereducea":"Reduce",
    "printbarcodea":"Print Barcode",
    "employeeoutputa":"Employee Output",
    "externalreceivea":"External Receive",
    "bundleinputa":"Bundle Input",
    "reporta":"Report",
    "wipreporta":"WIP Report",
    "outputreporta":"Output Report",
    "docnoinquirya":"Doc No. Inquiry",
    "dctreporta":"dCT Report",
    "barcodeinquirya":"Barcode Information Inquiry",
    "wipandoutputlia":"Real-time Production Information Report ",

    "CUT_LINE":"CUT LINE",
    "PRODUCTION_LINE_CD":"SEW LINE",
    "JOB_ORDER_NO":"JO NO.",
    "COLOR_CD":"COLOR",
    "ORDER_QTY":"ORDER QTY",
    "CUT_QTY_TODAY":"CUT IN",
    "CUT_QTY_TOTAL":"T.CUT IN",
    "REDUCE_QTY_TODAY":"REDUCE QTY",
    "REDUCE_QTY_TOTAL":"T.REDUCE QTY",
    "CUT_OUT_TODAY":"CUT OUT",
    "CUT_OUT_TOTAL":"T.CUT OUT",
    "CUT_OUT_WIP":"CUT OUT WIP",
    "PRT_IN_TODAY":"PRT IN",
    "PRT_IN_TOTAL":"T.PRT IN",
    "PRT_OUT_TODAY":"PRT OUT",
    "PRT_OUT_TOTAL":"T.PRT OUT",
    "PRT_IN_OUT_WIP":"PRT WIP",
    "EMB_OUT_TODAY":"EMB OUT",
    "EMB_OUT_TOTAL":"T.EMB OUT",
    "EMB_OUT_WIP":"EMB WIP",
    "FUSING_OUT_TODAY":"FUSE OUT",
    "FUSING_OUT_TOTAL":"T.FUSE OUT",
    "FUSING_OUT_WIP":"FUSE WIP",
    "MATCHING_OUT_TODAY":"DC OUT",
    "MATCHING_OUT_TOTAL":"T.DC OUT",
    "MATCHING_OUT_WIP":"DC WIP",
    "DC_BEFORE_WIP":"WIP BEFORE DC",
    "DC_SEW_S_TOTAL":"T.DC WIP",
    "DC_SEW_C":"OUTPUT",
    "DC_SEW_C_TOTAL":"T.OUTPUT",
    "TWIP":"T.WIP",
    "DCT":"DCT",
    "CUT_QTY":"CUT QTY",
    "SEQ":"SEQ",

    "GRID_FIRST":"FIRSR",
    "GRID_LAST":"LAST",
    "GRID_NEXT":"NEXT",
    "GRID_PREVIOUS":"PREVIOUS",
    "GRID_ITEMSPERPAGE":"LINE/PAGE",
    "GRID_EMPTY":"EMPTY",
    "printsparebarcodea":"Print Spare Code",
    "GRID_SPAN1":"Data List:"


}