{
"headertitle":"CIPMS-Print Barcode",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"select":"--Select--",
"layno":"Lay no / Status",
"bundle":"Bundle",
"jobordernolabel":"JO",
"laynolabel":"Lay No",
"bundlelabel":"Bundle No.",
"queryjobutton":"Query JO",
"printbutton":"Print",
"footertitle":"Print Barcode",
"combinepart":"Combine Parts:",
"isprintpart":"Is Printing Parts:",
"errormessage":"Failure! Pls check your network and try again! Wrong Code:",
"errormessage1":"Sorry! Failure to print! Pls try again! Wrong Code:",
"loadingmessage":"System is running! Please wait a minute!",
"confirmmessage1":"Sorry! Pls input JO and select lay no first!",
"confirmmessage2":"Succeed in printing the bundle barcode which in your selected layno!",
"confirmmessage3":"Succeed in printing the bundle barcode! Failure Layno: ",
"confirmmessage4":"Sorry! All failure!",
"confirmmessage5":"  Failure reason:",
"printmessage1":"Sorry! Print failure! Pls. print again! Wrong Code:",
"printmessage2":"Sorry! The JO should not use CIPMS for Transfer",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"dctreporta":"dCT Report",
"outputreporta":"Output Report",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"processnotopen":"Sorry!This JO has unapproved unit price or has no data in MES.Please check it.",
"printsparebarcodea":"Print Spare Code"
}