{
"functionmenubutton":"Functions",
"headertitle":"CIPMS-Bundle Reduce",
"footertitle":"CIPMS",
"cancelbutton":"Logout",
"jotextlabel":"JO",
"laynoselectlabel":"Lay No.",
"bundlenoselectlabel":"Bundle No.",
"barcodelabel":"Bundle Barcode",
"reasonlabel":"Reason",
"reduceqtylabel":"Reduce Qty",
"outqtylabel":"WIP QTY",
"confirmbutton":"Confirm",
"cleanbutton":"Clear",
"reducetablelabel":"Reduce List",
"defecttablelabel":"Defect List",
"reasonselect":"--select--",
"errormessage":"Sorry, something wrong! Pls try again! Wrong Code:",
"loadingmessage":"System is running! Please wait a minute!",
"barcodescanmessage1":"Pls scan the right bundle barcode!",
"barcodescanmessage2":"Sorry! The bundle you scanned has been submitted!",
"confirmmessage1":"Sorry! MES bundle reduce is wrong!",
"confirmmessage2":"Succeed in reducing!",
"confirmmessage3":"Sorry! Reduce failure! Pls. try again! If fail again, pls. contact leader to have a check! Thx! Wrong Code: ",
"confirmmessage4":"Sorry! Reduce failure! CIPMS's WIP is not enough! Wrong Code: ",
"confirmmessage5":"Sorry! Reduce failure! MES's WIP is not enough! Wrong Code: ",
"confirmmessage6":"Sorry! Reduce failure! MES's WIP is null! Wrong Code: ",
"barcodescanmessage3":"Sorry! The JO is wrong!",
"barcodescanmessage4":"Sorry! There is no bundle in the layno!",
"barcodescanmessage5":"Sorry! No barcode in the bundle",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"outputreporta":"Output Report",
"dctreporta":"dCT Report",
"title1":"JO",
"title2":"Color",
"title3":"Size",
"title4":"Bundle",
"title5":"Reason",
"title6":"Qty",
"title7":"Part",
"title8":"Process",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"queryfactory":"--Change Factory--", 
"printsparebarcodea":"Print Spare Code",
"accounterror":"No Permession to Access this Factory for your Account ID!"
}