{ 
"headertitle":"CIPMS-登录",
"footertitle":"CIPMS",
"footertitle":"裁床内部裁片管理系统",
"contenttitle":"登录",
"userbarcodelabel":"用户条码",
"loginbutton":"登录",
"registerbutton":"注册",
"errormessage":"对不起！请检查您的网路并重试！错误代码:",
"loadingmessage":"系统正在运作，请耐心等待！",
"alert1":"对不起！请先扫描用户条码！",
"alert2":"对不起！用户条码错误！请重新扫描！",
"alert3":"对不起！该用户条码没有系统功能权限！"
}