{
"headertitle":"CIPMS-WIP Report",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"jolabel":"JO:",
"golabel":"GO:",
"querybutton":"Query",
"exportbutton":"Export Excel",
"processlabel":"Process",
"bundlecheckboxlabel":"By Bundle",
"partcheckboxlabel":"By Part",
"colorsizecheckboxlabel":"By Color/Size",
"select":"--Select--",
"wiplabel":"WIP report:",
"linetablelabel":"Line WIP：",
"jotablelabel":"JO WIP：",
"errormessage":"Sorry! Something wrong! Pls check your network! Wrong Code:",
"loadingmessage":"System is running! Please wait a minute!",
"querymessage2":"Sorry! No data!",
"querymessage1":"The result is null!",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"outputreporta":"Output Report",
"docnoinquirya":"Doc No. Inquiry",
"dctreporta":"dCT Report",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"table14":"CUT_LINE",
"table15":"ORDER_QTY",
"table16":"CUT_QTY",
"table17":"SEW_LINE",
"table1":"NO.",
"table2":"JOB_ORDER_NO",
"table3":"Color",
"table4":"Size",
"table12":"Bundle_NO",
"table5":"Part",
"table6":"CUT_QTY",
"table7":"CUT",
"table8":"PRT",
"table9":"EMB",
"table10":"Matching",
"table11":"DC",
"table13":"SEW",
"queryfactory":"--Change Factory--", 
"printsparebarcodea":"Print Spare Code",
"accounterror":"No Permession to Access this Factory for your Account ID!"

}