 {
"headertitle":"CIPMS-Print Spare Barcode",
"footertitle":"CIPMS-Print Spare Code",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"select":"--Select--",
"gonolabel":"GO",
"colorlabel":"Color",
 "laynolabel":"Lay NO",
"patternlabel":"Paper Pattern",
"batchnolabel":"Batch No",
"shadelotlabel":"Shade Lot",
"querygobutton":"Query GO",
"printbutton":"Print",
"combinepart":"Printing Parts:",
"isprintpart":"Sizes Qty:",
"errormessage":"Failure! Pls check your network and try again! Wrong Code:",
"errormessage1":"Sorry! Failure to print! Pls try again! Wrong Code:",
"loadingmessage":"System is running! Please wait a minute!",
"confirmmessage1":"Sorry! Pls input GO and select color first!",
"confirmmessage2":"Succeed in printing the bundle barcode which in your selected condition!",
"confirmmessage3":"Succeed in printing the bundle barcode! Failure detail: ",
"confirmmessage4":"Sorry! All failure!",
"confirmmessage5":"  Failure reason:",
"confirmmessage6":" Please select the print part!",
"confirmmessage7":" Please input size num!",
"confirmmessage8":" max lay no：",
 "confirmmessage9":" Please input max lay no+1 to  the  lay no  text",
"confirmmessage10":"Do not input lay no and select lay no  to print at the same time ",
"printmessage1":"Sorry! Print failure! Pls. print again! Wrong Code:",
"printmessage2":"Sorry! The JO should not use CIPMS for Transfer",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"dctreporta":"dCT Report",
"outputreporta":"Output Report",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"processnotopen":"Sorry!This JO has unapproved unit price or has no data in MES.Please check it.",
 "printsparebarcodea":"Print Spare Code",
 "overprint":"Recover Print"
}