{
"headertitle":"CIPMS-打印印花士啤菲纸",
 "footertitle":"打印印花士啤菲纸",
"functionmenubutton":"功能选择",
"cancelbutton":"注销",
"select":"--选择--",
"gonolabel":"GO",
"colorlabel":"颜色",
"laynolabel":"床次",
"patternlabel":"纸样",
"batchnolabel":"缸号",
"shadelotlabel":"色级",
"querygobutton":"查询制单号",
"printbutton":"打印",
"combinepart":"印花部件选择:",
"isprintpart":"数量录入:",
"errormessage":"对不起！请检查您的网络并重试！错误代码：",
"errormessage1":"对不起！打印失败！请重试！错误代码：",
"loadingmessage":"系统正在运作，请耐心等待！",
"confirmmessage1":"对不起！请先选择GO和颜色或输入床号！",
"confirmmessage2":"成功打印全部选择条件菲纸！",
"confirmmessage3":"成功打印菲纸！失败记录：",
"confirmmessage4":"全部打印失败！",
"confirmmessage5":"  失败原因：",
"confirmmessage6":" 请选择要打印的印花部件！",
"confirmmessage7":" 请输入尺码数量！",
"confirmmessage8":" 目前系统最大床号为:",
"confirmmessage9":", 请以'最大床号+1' 为床号重新输入 ",
"confirmmessage10":"请不要同时输入床次和选择床次打印! ",
"printmessage1":"对不起！全部数据打印失败！请再次尝试！错误代码：",
"printmessage2":"对不起！该单不能在CPMIS进行流转！",
"packagea":"装箱",
"matchinga":"DC配套",
"transactiona":"流转",
"receivea":"接收",
"bundlereducea":"下数",
"printbarcodea":"打印菲纸",
"employeeoutputa":"员工产量",
"externalreceivea":"外部入数",
"bundleinputa":"按扎入数",
"reporta":"报表",
"wipreporta":"WIP报表",
"dctreporta":"dCT报表",
"outputreporta":"流转产量报表",
"barcodeinquirya":"扎/箱信息查询",
"docnoinquirya":"流水单信息查询",
"processnotopen":"对不起！该单在MES系统没有开工序！请检查！",
"wipandoutputlia":"实时生产信息报表",
"printsparebarcodea":"打印印花士啤菲纸",
"overprint":"覆盖打印"

}