{
"prevbutton":"Prev",
"nextbutton":"Next",
"pdtitle":"Print",
"pdbutton":"Print",
"headertitle":"CIPMS-Transaction/Rework/Adjustment",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"adjustmentradiolabel":"Adjustment",
"reworkradiolabel":"Rework",
"transactionradiolabel":"Transaction",
"cancelbutton":"Logout",
"barcodelabel":"Barcode",
"processtypelabel":"PRC Type",
"contractnolabel":"Contract No",
"partlabel":"Part",

"totalbundlelabel":"Total Bundles:",
"totalgarmentpcslabel":"Total Garment Pcs:",

"totalpartlabel":"Total Part:",
"totalpcslabel":"Total Part Pcs:",

"confirmbutton":"Confirm",
"submitbutton":"Submit",
"unsubmitbutton":"Unsubmit",
"reprintbutton":"Reprint",
"emptylistbutton":"Clear",
"savebutton":"Save",
"querybutton":"--Query--",
"fromfactoryselectlabel":"From:",
"nextfactorylabel":"To:",
"nextfactoryselect":"--Factory--",
"nextprocessselect":"--Process--",
"nextproductionlineselect":"--Production Line--",
"select":"--Select--",
"reasonselect":"--Select--",
"headertitle1":"Defect",
"barcodelabel1":"Bundle Barcode",
"existingqytlabel":"WIP",
"qtylabel":"Defect Qty",
"reasonlabel":"Defect Reason",
"reducetablelabel":"Defect List",
"defectselected":"Select",
"defecttabletitle1":"Process",
"defecttabletitle2":"Bundle Barcode",
"defecttabletitle3":"Part",
"defecttabletitle4":"Defect_Qty",
"defecttabletitle5":"Defect_Reason",
"defecttabletitle6":"Defect_Reason_CD",
"messageth":"Message",
"barcodelistlabel":"Bundle List",
"customer":"Customer",
"date":"Date Time",
"process":"From Dept",
"production":"From Line",
"part":"Part",
"summary":"Summary",
"jo":"JO NO.",
"color":"Color",
"cutqty":"CUT QTY",
"layno":"LAY NO",
"bundle":"TOTAL BUNDLE",
"totalqty":"TOTAL QTY",
"cartonbarcode":"Carton Barcode",
"errormessage":"Sorry! Something wrong! Pls check your network! Wrong Code:",
"errormessage2":"Sorry! Something wrong with the application! Wrong Code:",
"errormessage3":"Sorry! Transaction failure! Pls try again, thx!",
"errormessage4":"Transaction successfully! But it can not print DOC_NO, you can try reprinting DOC_NO:",
"errormessage5":"Sorry! Something wrong with bundle check! Wrong Code:",
"errormessage6":"Sorry! Transaction failure! Wrong Code:",
"errormessage7":"Sorry! Transaction successfully! But something wrong with print DOC_NO! Wrong Code:",
"errormessage8":"Sorry! Transfer failure! Wrong Code:831! Wrong Reason:",
"statusmessage1":"Sorry! The barcode scanned is in submit!",
"statusmessage2":"Sorry! The barcode scanned is in different process!",
"statusmessage3":"Sorry! The barcode scanned is not have full parts!",
"statusmessage4":"Sorry! The barcode scanned is in different receive process/production!",
"statusmessage5":"Sorry! The barcode scanned is in different send process/production!",
"statusmessage6":"Sorry! Something wrong with bundle check! Pls. try again!",
"statusmessage7":"Sorry! The bundle you scanned exists multiple garment_type in CUT!",
"statusmessage8":"Sorry! The bundle you scanned exists multiple garment_type in SEW!",
"statusmessage9":"Sorry! WIP over! Wrong code:",
"statusmessage10":"Sorry! Exists double WIP!",
"statusmessage11":"Sorry! Last process' output is less than the adjustment WIP!",
"statusmessage12":"Sorry! The bundle scanned are not in matching!",
"statusmessage13":"Sorry! The carton of the bundles you scanned is not in your process!",
"statusmessage14":"Sorry! The carton of the bundles you scanned is not full!",
"statusmessage15":"Sorry! The bundle you scanned are not in matching!",
"statusmessage16":"Sorry! The bundle you scanned is in carton! Pls. scan carton barcode!",
"loadingmessage":"System is running! Please wait a minute!",
"deletemessage1":"Succeed in deleting the bundle part:",
"deletemessage2":"Succeed in deleting the carton:",
"deletemessage3":"Succeed in deleting all the bundles!",
"selectpartmessage1":"Have selected parts:",
"emptymessage":"Have cleared the UI!",
"savemessage1":"Succeed in saving the bundle list!",
"savemessage2":"Failure! Pls scan barcode first!",
"querymessage1":"Succeed in querying the bundle parts:",
"querymessage2":" has been queried before!",
"reprintmessage1":"Sorry! There is no DOC_NO!",
"reprintmessage2":"Sorry! There are many DOC_NOs!",
"reprintmessage3":"Succeed in reprinting the DOC_NO: ",
"bundlescanmessage1":"Succeed in scanning the bundle part:",
"bundlescanmessage2":"Sorry! Get data failure! Pls. try to scan the next bundle!",
"bundlescanmessage3":"Sorry! The barcode you scan is not existent!Pls scan the right bundle or carton barcode!",
"bundlescanmessage4":"Pls select part first before scanning the bundle!",
"bundlescanmessage10":"Succeed in scanning the carton barcode:",
"bundlescanmessage10":"Succeed in scanning the DOC_NO :",
"bundlescanmessage5":"Pls select next factory and next process first!",
"bundlescanmessage6":"Pls select next production line first!",
"bundlescanmessage7":"You can not scan the bundle barcode which in Carton!",
"bundlescanmessage8":"The bundle barcode you scanned is not in ",
"bundlescanmessage9":", it is in",
"bundlescanmessage11":"Sorry! The bundle has been outsource. Can not do it again!",
"bundlescanmessage12":"Sorry! Pls matching the panel first!",
"bundlescanmessage13":"Sorry! You can not transfer multiple productions!",
"bundlescanmessage15":"Sorry! The bundle part you scanned is not existent!",
"partselectmessage1":"Pls select parts first before scanning the bundle!",
"cartonscanmessage1":"Sorry! The carton barcode is not exsitent!",
"cartonscanmessage2":"Pls select next production line first!",
"cartonscanmessage3":"The carton has been scanned before!",
"cartonscanmessage4":"There is not any bundle in this Carton!",
"cartonscanmessage5":"Succeed in scanning the Carton: ",
"cartonscanmessage6":"The carton is empty!",
"cartonscanmessage7":"The carton barcode you scan is not in the Contract No!",
"cartonscanmessage8":"Some of the bundle has been submitted!",
"cartonscanmessage9":"Sorry! The bundle did not matching, pls matching first!",
"docnoscanmessage1":"Succeed in scanning the DOC_NO: ",
"docnoscanmessage2":"You have scanned the DOC_NO before!",
"rejectdialogmessage1":"Pls input the whole informations!",
"defectmessage1":"Sorry! Defect is more than WIP!",
"defectmessage2":"Sorry! Pls input numbers!",
"confirmmessage1":"Transaction submit successfully! The new DOC_NO is ",
"confirmmessage4":"Transaction confirm successfully! The new DOC_NO is ",
"confirmmessage2":"Succeed in rework the bundles to process ",
"confirmmessage10":"Succeed in adjust the bundles to process ",
"confirmmessage9":", the new DOC_NO is ",
"confirmmessage3":"Outsource successfully! The new DOC_NO is ",
"confirmmessage5":"Pls select the next production_line first!",
"confirmmessage6":"Sorry! Failure to GTN transfer! Some bundles can not be transfered. Pls have a check!",
"confirmmessage7":"Succeed in GTN transfer! And print new DOC_NO:",
"confirmmessage8":"GTN failure！isexceedwip=true！",
"confirmmessage11":"Sorry! There are some bundles not in matching!",
"confirmmessage12":"Transfer successfully! But print failure! Pls. use reprint DOC_NO:",
"confirmmessage13":"Sorry! The data between CIPMS and MES are different! Pls. have a check!",
"confirmmessage14":"! Auto matching successfully!",
"confirmmessage15":"! Auto matching failure! Reason: ",
"submitmessage1":"Submit successfully! The DOC NO.is ",
"processmessage":"Pls select next process!",
"oasbundlemessage1":"Pls select the Contract No first!",
"oasbundlemessage2":"You can not just scan the bundle barcode which in the Carton! Pls scan the Carton barcode!",
"oasbundlemessage3":"The bundle barcode you scan is not in the Contract No!",
"unsubmitmessage1":"Succeed in unsubmitting the DOC_NO:",
"unsubmitmessage2":"Sorry! You can not unsubmit the DOC_NO!",
"unsubmitmessage3":"Sorry! The DOC_NO mismatches with the bundle you scanned!",
"unsubmitmessage4":"Sorry! The DOC_NO does not belong to your department!",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"outputreporta":"Output Report",
 "printsparebarcodea":"Print Spare Code",
"dctreporta":"dCT Report",
"docnoinquirya":"Doc No. Inquiry",
"user":"User:",
"datetime":"Date Time",
"fromdept":"From Dept",
"fromline":"From Line",
"cartonnum":"Carton Qty",
"automatching":"Auto Matching",
"toline":"To Line",
"parts":"Part",
"remark":"Remark",
"customer":"Customer:",
"summary":"Summary",
"jo":"JO NO.",
"doc":"DOC NO. ",
"color":"Color",
"layno":"LAY NO",
"bundles":"TOTAL BUNDLE",
"totalqty":"TOTAL QTY",
"totalcutqty":"TOTAL CUT QTY",
"currenttotalqty":"CURRENT TOTAL QTY",
"totaloutputqty":"TOTAL OUTPUT QTY",
"residualqty":"TOTAL RESIDUAL QTY",
"s":"'s",
"tabletranslation0":"DOC_NO.",
"tabletranslation1":"Carton",
"tabletranslation2":"Process",
"tabletranslation3":"Bundle_Barcode",
"tabletranslation4":"Part",
"tabletranslation5":"JO",
"tabletranslation6":"Bundle_no",
"tabletranslation7":"Lay_no",
"tabletranslation8":"Color",
"tabletranslation9":"Size",
"tabletranslation10":"Cut_Qty",
"tabletranslation11":"Output",
"tabletranslation12":"Reduce",
"tabletranslation13":"Defect",
"tabletranslation14":"Delete",
"dialogmessage3":"Attention:",
"dialogmessage9":"Confirm",
"dialogmessage10":"Cancel",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"queryfactory":"--Change Factory--", 
"accounterror":"No Permession to Access this Factory for your Account ID!",
"print_1":"Total bundle",
"print_2":"Caton NO#",
"print_3":"Bundle Barcode",
"print_4":"Part",
"print_5":"Color",
"print_6":"Lay NO.",
"print_7":"Bundle NO.",
"print_8":"Size",
"print_9":"QTY",
"print_10":" ",
"carnolabel":"CAR NO. :",
"carnotip":"Please input CAR NO#！"
}