{
"prevbutton":"Prev",
"nextbutton":"Next",
"pdtitle":"Print",
"pdbutton":"Print",
"headertitle":"CIPMS-Package",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"messageth":"Message",
"closeboxbutton":"Close Carton",
"openboxbutton":"Open Carton",
"checkbutton":"Check Carton",
"printbutton":"Print Carton",
"matchingbutton":"Matching",
"emptylistbutton":"Clear",
"savebutton":"Save",
"querybutton":"--Query--",
"jotextlabel":"JO NO.",
"partselectlabel":"Part",
"laynoselectlabel":"Lay No",
"colorselectlabel":"Color Code",
"bundlebarcodelabel":"Scan Barcode",
"cartonbarcodelabel":"Check Barcode",

"totalbundlelabel":"Total Bundles:",
"totalgarmentpcslabel":"Total Garment Pcs:",
"totalpartlabel":"Total Part:",
"totalpcslabel":"Total Part Pcs:",

"barcodelistlabel":"Bundle List",
"select":"--Select--",
"deletebutton":"Delete",
"customer":"Customer",
"date":"Date Time",
"process":"From Dept",
"production":"Cut Line",
"sewline":"Sew Line",
"ttlbundle":"TTL Bundle",
"shortpart":"Remain Parts",
"part":"Part",
"summary":"Summary",
"jo":"JO NO.",
"color":"Color",
"cutqty":"CUT QTY",
"layno":"LAY NO",
"bundle":"TOTAL BUNDLE",
"totalqty":"TOTAL QTY",
"cartonbarcode":"Carton Barcode",
"joinputmessage1":"Pls input the right JO NO. first!",
"joinputmessage2":"Sorry! It is failure to query the parts and laynos of the JO! Pls try again!",
"deletemessage1":"Succeed in deleting the bundle ",
"deletemessage2":"Succeed in deleting the carton ",
"emptylistmessage":"Succeed in clearing the bundle list",
"clearmessage":"Sorry, pls click clear button to clear UI!",
"partselectmessage1":"Succeed in get the part and layno information of the JO!",
"querymessage1":"Succeed in get the query information",
"partselectmessage2":"Sorry, pls select part before you scan bundle barcode!",
"bundlescanmessage1":"Sorry, the barcode you scan is not existent!",
"bundlescanmessage2":"You had scanned this bundle barcode before!",
"bundlescanmessage3":"Succeed in scanning this barcode",
"bundlescanmessage5":"Sorry! You just can scan the bundle barcode which in the same DOC_NO!",
"bundlescanmessage6":"Sorry! The bundle you scanned is not in OAS!",
"bundlescanmessage7":"Sorry! The bundle you scanned does not belong to the JO which you input!",
"bundlescanmessage8":"Sorry! The bundle has no remaining part!",
"bundlescanmessage9":"Sorry! The bundle part you scan is not in your process!",
"bundlescanmessage10":"Sorry! The bundles you scan are all in main carton!",
"bundlescanmessage11":"Sorry! The bundles you scan are all in main carton and second carton!",
"cartonscanmessage1":"The carton barcode is not existent!",
"cartonscanmessage2":"The carton is empty!",
"cartonscanmessage3":"The carton is opened!",
"cartonscanmessage4":"Succeed in scanning and querying the carton ",
"laynoselectmessage1":"Sorry, pls select part before you select lay no!",
"laynoselectmessage2":"You have selected the lay no before!",
"laynoselectmessage3":"Succeed in querying the bundle information in this lay no!",
"laynoselectmessage4":"Sorry! The parts you select are neither main carton's part nor second carton's part! Pls select the right parts!",
"laynoselectmessage5":"Sorry! The bundle of layno are all in carton!",
"laynoselectmessage6":"Sorry! The budnle of layno are all in main carton!",
"laynoselectmessage7":"Sorry! No second carton!",
"matchingmessage1":"Sorry, you have to scan the complete bundle!",
"matchingmessage2":"Sorry, something wrong with the bundle you scan! Pls have a check!",
"matchingmessage3":"Succeed in MATCHING and print an new carton barcode ",
"errormessage":"Sorry, pls check your network and have a second try! Wrong Code:",
"errormessage2":"Sorry, something wrong with application. Wrong Code:",
"loadingmessage":"System is running! Please wait a minute!",
"checkmessage1":"The bundle you scan is more than carton bundle:",
"checkmessage2":"Carton bundle is more than the bundle you scan:",
"checkmessage3":"Lack: ",
"opencartonmessage1":"Sorry, something wrong with the bundle you scan! Pls have a check!",
"opencartonmessage2":"Sorry, pls scan the complete bundles!",
"opencartonmessage3":"Succeed in opening the carton!",
"opencartonmessage4":"Sorry! You can not open this main carton which has second carton!",
"closecartonmessage1":"Sorry, something wrong with the carton! Pls have a check!",
"closecartonmessage2":"Sorry, the carton you scan is not existent!",
"closecartonmessage3":"Sorry, something wrong with the bundle you scan! Pls have a check!",
"closecartonmessage4":"Succeed in closing the carton ",
"closecartonmessage5":"Succeed in closing! The new carton barcode is  ",
"closecartonmessage6":"Sorry! The bundles you scan are not in the same main carton!",
"closecartonmessage7":"Sorry! The bundle just can be closed to two cartons!",
"closecartonmessage8":"Sorry! All the bundles' parts should be the same!",
"closecartonmessage9":"Sorry! The bundle you scan are not in the same GO!",
"closecartonmessage10":"Sorry! The bundle you scan are not in the same main Carton!",
"closecartonmessage11":"Sorry! Pls scan all the remaining parts for this bundle!",
"closecartonmessage12":"Sorry! The main carton of the second carton is not in closed!",
"closecartonmessage13":"Sorry! The carton is not in your process!",
"closecartonmessage14":"Sorry! The carton is not in your factory!",
"savemessage1":"Succeed in saving! The save time is ",
"querymessage2":"You have queried ",
"querymessage3":"Succeed in querying ",
"cartoninputmessage1":"Sorry! The carton you scan is not existent!",
"cartoninputmessage2":"Succeed in scanning the carton barcode ",
"reprintmessage1":"Succeed in scanning the old carton barcode ",
"reprintmessage2":"Sorry, the carton you sacn is opened or not existent!",
"reprintmessage3":"Sorry, the bundle you sacn is opened or not existent!",
"reprintmessage4":"Sorry, the bundle you sacn is not in carton!",
"barcodemessage1":"Sorry! You just can scan the bundle barcode!",
"barcodemessage2":"Sorry! You just can scan the bundle barcode which comes from the same factory!",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"dctreporta":"dCT Report",
"outputreporta":"Output Report",
"printsparebarcodea":"Print Spare Code",
"dialogmessage1":"OK",
"dialogmessage2":"Cancel",
"dialogmessage3":"Attention:",
"more":"1. Scanned panel more:",
"less":"2. Scanned panel less:",
"pcs":"Total pcs:",
"bundles":"Total bundle:",
"s":"'s ",
"detail":"Detail:",
"title1":"Carton",
"title2":"Process",
"title3":"Bundle_Barcode",
"title4":"Part",
"title5":"JO",
"title6":"Bundle_no",
"title7":"Lay_no",
"title8":"Color",
"title9":"Size",
"title10":"Cut_Qty",
"title11":"Output",
"title12":"Defect",
"title13":"Reduce",
"dialogmessage3":"Attention:",
"dialogmessage7":"Are you sure to close bundles's (",
"dialogmessage8":") into the first main Carton? Pls confirm!",
"dialogmessage9":"Confirm",
"dialogmessage10":"Cancel",
"dialogmessage11":"（Remain Part：",
"dialogmessage12":"）",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"emb":"EMB",
"prt":"PRINT",
"embafterprt":"EMB AFTER PRINT",
"prtsp":"PRINT士啤",
"colormessage1":"Incorrect Color For The Barcode/Carton"
}