{
"headertitle":"CIPMS-流转产量报表",
"footertitle":"CIPMS",
"functionmenubutton":"功能选择",
"cancelbutton":"注销",
"jotext":"制单号",
"gotext":"GO NO.",
"fromdatelabel":"From Date",
"outputlabel":"输出查询结果：",
"linetablelabel":"组别层次WIP：",
"jotablelabel":"JO层次WIP：",
"todatelabel":"To Date",
"jobutton":"查询",
"datebutton":"查询",
"select":"--选择--",
"datesure":"确定",
"datecancel":"取消",
"dateyear":"年",
"datemonth":"月",
"dateday":"日",
"errormessage":"对不起！请检查网络并且重新操作！错误代码:",
"loadingmessage":"系统正在运作，请耐心等待！",
"querymessage1":"对不起！起始日期不能大于结束日期！",
"querymessage2":"没有数据结果！",
"querymessage3":"请填写完整日期！",
"querymessage4":"对不起！您输入的JO不属于输入的GO！",
"querymessage5":"对不起！请输入查询信息！",
"querymessage6":"对不起！用户输入的JO和GO不匹配！",
"packagea":"装箱",
"matchinga":"DC配套",
"transactiona":"流转",
"receivea":"接收",
"bundlereducea":"下数",
"printbarcodea":"打印菲纸",
"employeeoutputa":"员工产量",
"externalreceivea":"外部入数",
"bundleinputa":"按扎入数",
"reporta":"报表",
"wipreporta":"WIP报表",
"outputreporta":"流转产量报表",
"dctreporta":"dCT报表",
"processlabel":"部门",
"nextprocesslabel":"接收部门",
"prtcheckboxlabel":"印花",
"embcheckboxlabel":"绣花",
"matchingcheckboxlabel":"Matching",
"dccheckboxlabel":"DC",
"bundlecheckboxlabel":"By Part(部件)",
"colorecheckboxlabel":"By Color(颜色)",
"title1":"部件",
"title2":"裁床",
"title3":"印花",
"title4":"绣花",
"title4a":"朴房",
"title5":"待配套",
"title6":"DC",
"title7":"总计",
"title8":"裁床组别",
"title9":"制单号",
"title10":"颜色",
"title11":"尺码",
"title12":"扎号",
"title13":"日期",
"title14":"产量",
"title15":"制单数",
"title16":"裁数",
"title17":"裁床组别",
"title18":"车缝组别",
"title19":"制单",
"title20":"颜色",
"title21":"尺码",
"addfield22":"By 车缝组别",
"addfield24":"By 颜色/尺码",
"barcodeinquirya":"扎/箱信息查询",
"docnoinquirya":"流水单信息查询",
"wipandoutputlia":"产量和WIP报表",
"queryfactory":"--转工厂--", 
"accounterror":"你的账号没有权限访问这个工厂",
"printsparebarcodea":"打印印花士啤菲纸",
"exportexcelbutton":"导出Excel"

}