{
"headertitle":"CIPMS-Output Report",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"jotext":"JO NO.",
"gotext":"GO NO.",
"outputlabel":"Output report:",
"linetablelabel":"Line WIP：",
"jotablelabel":"JO WIP：",
"fromdatelabel":"From Date",
"todatelabel":"To Date",
"jobutton":"Query",
"datebutton":"Query",
"select":"--Select--",
"datesure":"Ok",
"datecancel":"Cancel",
"dateyear":"Year",
"datemonth":"Month",
"dateday":"Day",
"errormessage":"Sorry! Something wrong! Pls check your network! Wrong Code:",
"loadingmessage":"System is running! Please wait a minute!",
"querymessage1":"Sorry! From date can not bigger than To date!",
"querymessage2":"No data!",
"querymessage3":"Pls input the whole date!",
"querymessage4":"Sorry! The JO you input does not belong to the GO you input!",
"querymessage5":"Sorry! Pls input the query condition!",
"querymessage6":"Sorry! JO and GO are not matching!",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"outputreporta":"Output Report",
"dctreporta":"dCT Report",
"processlabel":"Process",
"nextprocesslabel":"Next Process",
"prtcheckboxlabel":"PRT",
"embcheckboxlabel":"EMB",
"matchingcheckboxlabel":"Matching",
"dccheckboxlabel":"DC",
"bundlecheckboxlabel":"By Part",
"colorecheckboxlabel":"By Color",
"title1":"Part",
"title2":"CUT",
"title3":"PRT",
"title4":"EMB",
"title4a":"FUSE",
"title5":"Matching",
"title6":"DC",
"title7":"QTY",
"title8":"CUT_LINE",
"title9":"JOB_ORDER_NO",
"title10":"Color",
"title11":"Size",
"title12":"Bundle_No",
"title13":"Date",
"title14":"OUT_QTY",
"title15":"ORDER_QTY",
"title16":"CUT_QTY",
"title17":"CUT_LINE",
"title18":"SEW_LINE",
"title19":"JO",
"title20":"COLOR_CD",
"title21":"SIZE_CD",
"addfield22":"By SEW LINE",
"addfield24":"By COLOR/SIZE",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"queryfactory":"--Change Factory--", 
"accounterror":"No Permession to Access this Factory for your Account ID!",
"printsparebarcodea":"Print Spare Code",
"exportexcelbutton":"Export Excel"
}