{
"headertitle":"CIPMS-dCT Report",
"footertitle":"CIPMS",
"functionmenubutton":"Functions",
"cancelbutton":"Logout",
"fromdatelabel":"From Date",
"todatelabel":"To Date",
"datebutton":"Confirm",
"dctlabel":"dCT report:",
"select":"--Select--",
"datesure":"Ok",
"datecancel":"Cancel",
"dateyear":"Year",
"datemonth":"Month",
"dateday":"Day",
"errormessage":"Sorry! Something wrong! Pls check your network! Wrong Code:",
"querymessage1":"The result is null!",
"packagea":"Package",
"matchinga":"Matching",
"transactiona":"Transaction",
"receivea":"Receive",
"bundlereducea":"Reduce",
"printbarcodea":"Print Barcode",
"employeeoutputa":"Employee Output",
"externalreceivea":"External Receive",
"bundleinputa":"Bundle Input",
"reporta":"Report",
"wipreporta":"WIP Report",
"dctreporta":"dCT Report",
"outputreporta":"Output Report",
"title2":"CUT",
"title3":"PRT",
"title4":"EMB",
"title5":"Matching",
"title6":"DC",
"docnoinquirya":"Doc No. Inquiry",
"barcodeinquirya":"Barcode Information Inquiry",
"wipandoutputlia":"Real-time Production Information Report ",
"queryfactory":"--Change Factory--", 
"accounterror":"No Permession to Access this Factory for your Account ID!"
}